### PR TITLE
#57 new cli flag save single snapshot to file

### PR DESCRIPTION
**Pull request by dsidirop**
@wallyqs 

Let me know what you think. I'm only 90% sure that this fits the bill.

Any feedback welcome - Thank you in advance!

### CODE REVIEW

**Comment by wallyqs** [comment]
I think functionality looks good, could you rebase the branch on top of main to be able to merge? 
Thanks for the contribution!

**Comment by dsidirop** [comment]
Thank you for the prompt follow-up. I've resolved conflicts but not sure if that's enough - please let me know if there are additional steps that I must undertake @wallyqs

**Comment by wallyqs** [comment]
Thanks @dsidirop! I will do a release soon with your changes.

**Comment by dsidirop** [comment]
Thumbs up mate - appreciated! Quick question ("thinking out loud"): Would it make sense to introduce an additional flag on top of -o which would set the column-separator in the grid? For example if we want the generated text file to be used as .csv later on it would make sense to set the separator to ",".

Just an idea of the top of my head - let me know what you think.

**Pull request merged**
